module.exports = {
  //========================= Audit File Constants ====================
  auditFileLabel: "auditfile",

  //========================= Audit File Header Constants ====================
  auditFileHeaderLabel: "header",
  fiscalYearLabel: "fiscalYear",
  startDateLabel: "startDate",
  endDateLabel: "endDate",
  curCodeLabel: "curCode",
  dateCreatedLabel: "dateCreated",
  timeCreatedLabel: "timeCreated",
  softwareDescLabel: "softwareDesc",
  softwareVersionLabel: "softwareVersion",
  softwareCompanyNameLabel: "softwareCompanyName",
  auditfileVersionLabel: "auditfileVersion",
  headerCommentLabel: "headerComment",
  userIDLabel: "userID",

  //========================= Company Constants ====================
  companyIdentLabel: "companyIdent",
  companyNameLabel: "companyName",
  taxRegistrationCountryLabel: "taxRegistrationCountry",
  taxRegIdentLabel: "taxRegIdent",
  streetAddressLabel: "streetAddress",
  //Removed as not required
  //postalAddressLabel: "postalAddress",
  //customersSuppliersLabel: "customersSuppliers",
  //generalLedgerLabel: "generalLedger",

  //========================= Street Address Constants ====================
  streetnameLabel: "streetname",
  numberLabel: "number",
  buildingLabel: "building",
  additionalAddressDetailsLabel: "additionalAddressDetails",
  cityLabel: "city",
  postalCodeLabel: "postalCode",
  countryLabel: "country",

  //========================= General Ledger Constants ====================
  generalLedgerLabel: "generalLedger",
  ledgerAccountLabel: "ledgerAccount",
  accIDLabel: "accID",
  accDescLabel: "accDesc",

  //========================= Postal Address Constants ====================
  postalAddressLabel: "postalAddress",

  //========================= Vat Code Details Constants ====================
  vatCodeDetailsLabel: "vatCodeDetails",
  vatCodeDetailLabel: "vatCodeDetail",
  vatCodeLabel: "vatCode",
  dateOfEntryLabel: "dateOfEntry",
  vatDescLabel: "vatDesc",
  standardVatCodeLabel: "standardVatCode",

  //========================= Period Constants ====================
  periodsLabel: "periods",
  periodLabel: "period",
  periodNumberLabel: "periodNumber",
  periodDescLabel: "periodDesc",
  startDatePeriodLabel: "startDatePeriod",
  startTimePeriodLabel: "startTimePeriod",
  endDatePeriodLabel: "endDatePeriod",
  endTimePeriodLabel: "endTimePeriod",

  // ========================= Employee Constants ====================
  employeesLabel: "employees",
  employeeLabel: "employee",
  empIDLabel: "empID",
  dateOfEntryLabel: "dateOfEntry",
  timeOfEntryLabel: "timeOfEntry",
  firstNameLabel: "firstName",
  surNameLabel: "surName",
  employeeRoleLabel: "employeeRole",
  roleTypeLabel: "roleType",
  roleTypeDescLabel: "roleTypeDesc",

  // ========================= Article Constants ====================
  articlesLabel: "articles",
  articleLabel: "article",
  artIDLabel: "artID",
  dateOfEntryLabel: "dateOfEntry",
  artGroupIDLabel: "artGroupID",
  artDescLabel: "artDesc",

  // ========================= Basic Constants ====================
  basicsLabel: "basics",
  basicLabel: "basic",
  basicTypeLabel: "basicType",
  basicIDLabel: "basicID",
  predefinedBasicIDLabel: "predefinedBasicID",
  basicDescLabel: "basicDesc",

  // ========================= Location Constants ====================
  locationsLabel: "locations",
  locationLabel: "location",
  locationNameLabel: "name",

  // ========================= Cash Transaction Constants ====================
  cashregisterLabel: "cashresigter",
  registerIDLabel: "registerID",
  regDescLabel: "regDesc",
  eventLabel: "event",
  cashtransactionLabel: "cashtransaction",
  nrLabel: "nr",
  transIDLabel: "transID",
  transTypeLabel: "transType",
  transAmntInLabel: "transAmntIn",
  transAmntExLabel: "transAmntEx",
  amntTpLabel: "amntTp",
  empIDLabel: "empID",
  custSupIDLabel: "custSupID",
  periodNumberLabel: "periodNumber",
  transDateLabel: "transDate",
  transTimeLabel: "transTime",
  ctLineLabel: "ctLine",
  vatLabel: "vat",
  paymentLabel: "payment",
  trainingIDLabel: "trainingID",
  signatureLabel: "signature",
  keyVersionLabel: "keyVersion",
  certificateDataLabel: "certificateData",
  voidTransactionLabel: "voidTransaction",
  trainingIdLabel: "trainingId",
  //savingsLabel: "savings",
  //discountLabel: "discount",
  //raiseLabel: "raise",
  //roundingLabel: "rounding",
  // receiptNumLabel: "receiptNum",
  // receiptCopyNumLabel: "receiptCopyNum",

  // ========================= CTLine Constants ====================

  lineIDLabel: "lineID",
  lineTypeLabel: "lineType",
  artGroupIDLabel: "artGroupID",
  artIDLabel: "artID",
  qntLabel: "qnt",
  lineAmntInLabel: "lineAmntIn",
  lineAmntExLabel: "lineAmntEx",
  amntTpLabel: "amntTp",
  ppuLabel: "ppu",
  vatLabel: "vat",
  //empIDLabel: "empID",
  //lineDateLabel: "lineDate",
  //lineTimeLabel: "lineTime",
  // savingsLabel: "savings",
  // discountLabel: "discount",
  // raiseLabel: "raise",

  // ========================= VAT Constants ====================
  vatPercLabel: "vatPerc",
  vatAmntLabel: "vatAmnt",
  vatAmntTpLabel: "vatAmntTp",

  // ========================= Payment Constants ====================
  paymentTypeLabel: "paymentType",
  paidAmntLabel: "paidAmnt",
  empID: "empID",
  curCode: "curCode",
  staffData: [
    {
      _id: "66db69eb0dcca3d7f62010d5",
      staffName: "raya",
      firstname: "raya",
      lastname: "dinkova",
      dateOfEntry: "2023-03-01",
      timeOfEntry: "09:00:00",
    },
    {
      _id: "649d488ade37495047eb588c",
      staffName: "jose",
      firstname: "jose",
      lastname: "scioli",
      dateOfEntry: "2023-03-01",
      timeOfEntry: "09:00:00",
    },
    {
      _id: "649d48b9de37495047eb588e",
      staffName: "shreyash",
      firstname: "shreyash",
      lastname: "dhamane",
      dateOfEntry: "2023-05-01",
      timeOfEntry: "09:00:00",
    },
    {
      _id: "649d48f7de37495047eb5890",
      staffName: "sigrid",
      firstname: "sigrid",
      lastname: "birk",
      dateOfEntry: "2023-03-01",
      timeOfEntry: "09:00:00",
    },
    {
      _id: "649d4916de37495047eb5892",
      staffName: "sophus",
      firstname: "sophus",
      lastname: "hansen",
      dateOfEntry: "2023-03-01",
      timeOfEntry: "09:00:00",
    },
    {
      _id: "649d493ede37495047eb5894",
      staffName: "yu",
      firstname: "yu",
      lastname: "zhang",
      dateOfEntry: "2023-03-01",
      timeOfEntry: "09:00:00",
    },
    {
      _id: "649d495fde37495047eb5896",
      staffName: "florencia",
      firstname: "florencia",
      lastname: "medici",
      dateOfEntry: "2023-03-01",
      timeOfEntry: "09:00:00",
    },
    {
      _id: "649d4974de37495047eb5898",
      staffName: "valentina",
      firstname: "valentina",
      lastname: "cruz",
      dateOfEntry: "2023-03-01",
      timeOfEntry: "09:00:00",
    },
    {
      _id: "649d498cde37495047eb589a",
      staffName: "camila",
      firstname: "camila",
      lastname: "monte",
      dateOfEntry: "2023-03-01",
      timeOfEntry: "09:00:00",
    },
    {
      _id: "64b39ccfc0419791443cac85",
      staffName: "prasad",
      firstname: "prasad",
      lastname: "chougule",
      dateOfEntry: "2019-03-01",
      timeOfEntry: "09:00:00",
    },
    {
      _id: "66d371b9864eea6101283afc",
      staffName: "solene",
      firstname: "solene",
      lastname: "dhoudain",
      dateOfEntry: "2019-03-01",
      timeOfEntry: "09:00:00",
    },
    {
      _id: "66d371b9864eea6101283afc",
      staffName: "neha",
      firstname: "neha",
      lastname: "durugkar",
      dateOfEntry: "2019-03-01",
      timeOfEntry: "09:00:00",
    },
    {
      _id: "66d371b9864eea6101283afc",
      staffName: "gisela",
      firstname: "gisela",
      lastname: "cardona",
      dateOfEntry: "2019-03-01",
      timeOfEntry: "09:00:00",
    },
  ],
  bowlArticle: {
    artID: "17",
    artGroupID: "4",
    artDesc: "Indian Bowl",
    dateOfEntry: "2023-07-01",
  },
  plateArticle: {
    artID: "18",
    artGroupID: "5",
    artDesc: "Indian Plate",
    dateOfEntry: "2023-07-01",
  },
};
